### ISSUE TITLE
Auto-enable the bundle

### ISSUE THREAD

**Issue by nclavaud** [trompette/php-feature-toggles#10]
During setup, I had to register the `FeatureTogglesBundle` manually in `config/bundles.php`.

According to https://symfony.com/doc/current/bundles/best_practices.html#installation, this could be done automatically by Symfony Flex just by setting a `type: symfony-bundle` property in `composer.json`.

**Comment by trompette** [comment]
After thinking about it, the project is not a Symfony bundle: it is a standalone PHP library containing a bundle for Symfony users, and may one day contain integrations for other frameworks.

I guess the bundle registration step should at least be documented, and I will look into contributing a Symfony Flex recipe in the https://github.com/symfony/recipes-contrib repository.

**Comment by nclavaud** [comment]
Fair enough.

For the record, I gave it a try with a local fork of the repository, but failed: it would not install the bundle despite setting the `type` property :shrug: 

About the recipe, I found this note [in the official recipes repository](https://github.com/symfony/recipes#creating-recipes):
> Don't create a recipe for Symfony bundles if the only configuration in the manifest is the registration of the bundle for all environments, as this is done automatically.

but, well, I could not make it work, and your approach makes sense anyway.

**Comment by trompette** [comment]
I created #25 for the documentation update.

I think it will be enough for the moment.
