### ISSUE TITLE
Integrate with DoctrineMigrationsBundle

### ISSUE THREAD

**Issue by nclavaud** [trompette/php-feature-toggles#13]
The bundle provides a convenient console command to migrate the schema, but when using [DoctrineMigrationsBundle](https://symfony.com/doc/current/bundles/DoctrineMigrationsBundle/index.html), the newly created tables will get dropped by the next generated migration.

I know this is specific to DoctrineMigrationsBundle but still, as the FeatureTogglesBundle relies on DBAL by default, maybe it should be documented that the tables can be ignored using the `schema_filter` parameter:
https://symfony.com/doc/current/bundles/DoctrineMigrationsBundle/index.html#manual-tables

Or maybe there is a way to integrate with DoctrineMigrationsBundle seamlessly and let it generate the migration from the schema? I guess most people using migrations would prefer creating these tables in production with `docrine:migrations:migrate` rather than with the provided command, especially when migrations are part of the deployment process.

**Comment by trompette** [comment]
It looks like there is a way, indeed: https://symfony.com/blog/new-in-symfony-5-1-automatic-schema-updates.
